### PR TITLE
Update Status Handler to show all requests

### PR DESCRIPTION
**Pull request by evangrayk**
* add thread-safe MultiMapCounter to count requests and statuses
* show counts of URIs accessed and return code

### CODE REVIEW

**Comment by evangrayk** [comment]
Here is what it looks like:
screen shot 2017-02-24 at 6 53 16 pm

**Comment by joeydlee95** [comment]
looks great can we underline Webserver Status

**Comment by evangrayk** [comment]
Just for you Joey:
screen shot 2017-02-24 at 10 14 30 pm

**Comment by joeydlee95** [comment]
GREAT

**Pull request merged**
